/** @type {import('tailwindcss').Config} */
// Theme ported verbatim from the stitch_odoo_hack mockups' shared tailwind.config,
// with three additions the mockups referenced but never defined (body-sm, the 24px
// 2xl radius used by the itinerary builder, and body-caption).
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#43474f",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#2f1500",
        "on-secondary-container": "#603100",
        "inverse-surface": "#2e3132",
        surface: "#f8f9fa",
        "primary-container": "#003366",
        "tertiary-fixed": "#c6e7ff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9fa",
        "secondary-fixed": "#ffdcc3",
        primary: "#001e40",
        "on-primary-container": "#799dd6",
        "on-secondary-fixed-variant": "#6e3900",
        "surface-dark": "#121212",
        "primary-fixed": "#d5e3ff",
        "on-tertiary-container": "#00a6e5",
        "on-surface": "#191c1d",
        tertiary: "#002131",
        "outline-variant": "#c3c6d1",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#ffb77d",
        "on-error-container": "#93000a",
        "secondary-container": "#fd8b00",
        outline: "#737780",
        "surface-container-high": "#e7e8e9",
        "sunset-action": "#FF8C00",
        "ocean-deep": "#003366",
        ink: "#1A1A1A",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#a7c8ff",
        "error-container": "#ffdad6",
        "surface-container": "#edeeef",
        "on-background": "#191c1d",
        "on-tertiary-fixed-variant": "#004c6b",
        "on-secondary": "#ffffff",
        secondary: "#904d00",
        "on-primary-fixed": "#001b3c",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed": "#001e2d",
        "primary-fixed-dim": "#a7c8ff",
        "on-primary-fixed-variant": "#1f477b",
        "sky-tint": "#E1F5FE",
        background: "#f8f9fa",
        "surface-tint": "#3a5f94",
        "surface-dim": "#d9dadb",
        "tertiary-container": "#00374f",
        "tertiary-fixed-dim": "#83cfff",
        "surface-container-highest": "#e1e3e4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "body-caption": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
